import type { KmsData } from "@/lib/types";

export const seedData: KmsData = {
  role: "reviewer",
  knowledge: [
    {
      id: "panduan-struk-parkir",
      title: "Penggunaan struk untuk parkir",
      content:
        "Gunakan panduan ini saat pelanggan menanyakan fungsi bukti transaksi pada tahap parkir. Petugas memeriksa ketentuan aktif sebelum memberi arahan.",
      summary: "Panduan fungsi bukti transaksi pada tahap parkir.",
      category: "Aturan layanan",
      source: "Dokumen layanan terverifikasi",
      owner: "Penanggung jawab konten",
      touchpoints: ["Kasir", "Pelanggan", "Parkir"],
      status: "active",
      effectiveDate: "2026-09-01",
      expiryDate: "2026-09-30",
      activeVersionId: "ver-parkir-13",
    },
    {
      id: "faq-validasi-transaksi",
      title: "FAQ validasi bukti transaksi",
      content: "Jawaban singkat untuk pertanyaan validasi bukti transaksi dari kasir ke area parkir.",
      summary: "Perlu pemeriksaan sebelum dipakai sebagai jawaban.",
      category: "FAQ",
      source: "Catatan layanan internal",
      owner: "Pemilik konten layanan",
      touchpoints: ["Kasir", "Parkir"],
      status: "review",
      effectiveDate: "2026-09-18",
      expiryDate: "2026-10-18",
    },
    {
      id: "arsip-parkir-agustus",
      title: "Arsip ketentuan parkir periode lalu",
      content: "Ketentuan periode Agustus yang disimpan hanya untuk kebutuhan audit.",
      summary: "Hanya untuk riwayat; bukan panduan aktif.",
      category: "Arsip",
      source: "Dokumen layanan periode lalu",
      owner: "Penanggung jawab konten",
      touchpoints: ["Parkir"],
      status: "expired",
      effectiveDate: "2026-08-01",
      expiryDate: "2026-08-31",
      activeVersionId: "ver-arsip-10",
    },
    {
      id: "menu-paket-keluarga",
      title: "Detail paket keluarga",
      content: "Rincian item paket, pilihan lauk, serta item tambahan yang dikenakan biaya terpisah.",
      summary: "Detail paket perlu menjelaskan item tambahan secara konsisten.",
      category: "Menu & paket",
      source: "Daftar menu outlet",
      owner: "Pemilik konten menu",
      touchpoints: ["Menu", "Pemesanan", "Kasir"],
      status: "needs_revision",
      effectiveDate: "2026-09-01",
      expiryDate: "2026-12-31",
      activeVersionId: "ver-paket-10",
    },
    {
      id: "syarat-promo-akhir-pekan",
      title: "Syarat promo akhir pekan",
      content: "Promo berlaku pada Sabtu dan Minggu untuk metode pembayaran terpilih dengan minimum transaksi Rp200.000.",
      summary: "Syarat pembayaran dan periode promo diperjelas.",
      category: "Promosi & pembayaran",
      source: "Dokumen ketentuan promosi",
      owner: "Pemilik konten promosi",
      touchpoints: ["Kasir", "Pelanggan", "Pembayaran"],
      status: "review",
      effectiveDate: "2026-09-06",
      expiryDate: "2026-09-27",
      activeVersionId: "ver-promo-11",
    },
    {
      id: "panduan-item-tambahan",
      title: "Panduan biaya item tambahan",
      content: "Pastikan pelanggan mengetahui item tambahan yang tidak termasuk paket sebelum pesanan dikonfirmasi.",
      summary: "Konfirmasi biaya tambahan sebelum pemesanan.",
      category: "Menu & paket",
      source: "Daftar menu outlet",
      owner: "Pemilik konten menu",
      touchpoints: ["Menu", "Pemesanan"],
      status: "active",
      effectiveDate: "2026-09-01",
      expiryDate: "2026-12-31",
      activeVersionId: "ver-item-10",
    },
  ],
  versions: [
    {
      id: "ver-parkir-13",
      knowledgeId: "panduan-struk-parkir",
      version: "v1.3",
      changeSummary: "Penjelasan touchpoint kasir dan parkir diperjelas.",
      content: "Kasir menyampaikan kegunaan struk, pelanggan menyimpannya, dan petugas parkir memverifikasi aturan aktif.",
      creator: "Pemilik konten layanan",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-20T09:30:00.000Z",
      status: "active",
      sourceVerified: true,
    },
    {
      id: "ver-parkir-12",
      knowledgeId: "panduan-struk-parkir",
      version: "v1.2",
      changeSummary: "Istilah bukti transaksi diseragamkan.",
      content: "Pelanggan menyimpan bukti transaksi untuk proses parkir.",
      creator: "Pemilik konten layanan",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-12T10:15:00.000Z",
      status: "archived",
      sourceVerified: true,
    },
    {
      id: "ver-parkir-11",
      knowledgeId: "panduan-struk-parkir",
      version: "v1.1",
      changeSummary: "Draf awal panduan layanan.",
      content: "Bawa struk untuk kebutuhan parkir.",
      creator: "Pemilik konten layanan",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-01T08:00:00.000Z",
      status: "archived",
      sourceVerified: true,
    },
    {
      id: "ver-arsip-10",
      knowledgeId: "arsip-parkir-agustus",
      version: "v1.0",
      changeSummary: "Ketentuan parkir periode Agustus ditetapkan.",
      content: "Ketentuan periode Agustus yang disimpan untuk kebutuhan audit.",
      creator: "Penanggung jawab konten",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-08-01T08:00:00.000Z",
      status: "expired",
      sourceVerified: true,
    },
    {
      id: "ver-item-10",
      knowledgeId: "panduan-item-tambahan",
      version: "v1.0",
      changeSummary: "Panduan biaya item tambahan diterbitkan.",
      content: "Pastikan pelanggan mengetahui item tambahan yang tidak termasuk paket sebelum pesanan dikonfirmasi.",
      creator: "Pemilik konten menu",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-01T08:30:00.000Z",
      status: "active",
      sourceVerified: true,
    },
    {
      id: "ver-promo-12",
      knowledgeId: "syarat-promo-akhir-pekan",
      version: "v1.2",
      changeSummary: "Syarat pembayaran diperjelas.",
      content: "Promo Sabtu–Minggu, minimum transaksi Rp200.000, menggunakan kartu terpilih, dan tidak dapat digabung.",
      creator: "Pemilik konten promosi",
      status: "review",
      sourceVerified: true,
    },
    {
      id: "ver-promo-11",
      knowledgeId: "syarat-promo-akhir-pekan",
      version: "v1.1",
      changeSummary: "Versi awal promo akhir pekan.",
      content: "Promo berlaku pada akhir pekan untuk pembayaran kartu.",
      creator: "Pemilik konten promosi",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-01T08:00:00.000Z",
      status: "active",
      sourceVerified: true,
    },
    {
      id: "ver-paket-11",
      knowledgeId: "menu-paket-keluarga",
      version: "v1.1",
      changeSummary: "Item tambahan dicantumkan.",
      content: "Paket keluarga berisi empat pilihan lauk. Minuman dan item tambahan dikenakan biaya terpisah.",
      creator: "Pemilik konten menu",
      status: "needs_revision",
      sourceVerified: false,
    },
    {
      id: "ver-paket-10",
      knowledgeId: "menu-paket-keluarga",
      version: "v1.0",
      changeSummary: "Versi awal detail paket.",
      content: "Paket keluarga berisi empat pilihan lauk.",
      creator: "Pemilik konten menu",
      reviewer: "Reviewer KMS",
      approvalTime: "2026-09-01T08:00:00.000Z",
      status: "active",
      sourceVerified: true,
    },
  ],
  promotions: [
    {
      id: "promo-makan-siang",
      name: "Paket makan siang",
      status: "active",
      minimumTransaction: 150000,
      paymentMethods: ["Kartu terpilih"],
      periodStart: "2026-09-01",
      periodEnd: "2026-09-30",
      quotaNotes: "Kuota harian berlaku",
      exceptions: ["Tidak dapat digabung dengan promo lain"],
    },
    {
      id: "promo-kartu-bank",
      name: "Promo kartu bank terpilih",
      status: "ending_soon",
      minimumTransaction: 250000,
      paymentMethods: ["Kartu kredit terpilih"],
      periodStart: "2026-09-10",
      periodEnd: "2026-09-24",
      quotaNotes: "Tersedia selama kuota masih ada",
      exceptions: ["Tidak berlaku untuk item tambahan"],
    },
    {
      id: "promo-agustus",
      name: "Promo keluarga periode Agustus",
      status: "archived",
      minimumTransaction: 200000,
      paymentMethods: ["Tunai", "Kartu debit"],
      periodStart: "2026-08-01",
      periodEnd: "2026-08-31",
      quotaNotes: "Periode telah berakhir",
    },
  ],
  reviews: [
    {
      id: "review-promo-12",
      knowledgeId: "syarat-promo-akhir-pekan",
      versionId: "ver-promo-12",
      submittedBy: "Pemilik konten promosi",
      submittedAt: "2026-09-21T08:45:00.000Z",
      status: "review",
    },
    {
      id: "review-paket-11",
      knowledgeId: "menu-paket-keluarga",
      versionId: "ver-paket-11",
      submittedBy: "Pemilik konten menu",
      submittedAt: "2026-09-20T13:10:00.000Z",
      status: "needs_revision",
    },
  ],
  reports: [],
};

export function cloneSeedData(): KmsData {
  return JSON.parse(JSON.stringify(seedData)) as KmsData;
}
